[tool.poetry]
name = "aloud"
version = "0.1.0"
description = ""
authors = ["Gilad Barnea <giladbrn@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
elevenlabs = "^0.2.18"
black = "^23.3.0"
isort = "^5.12.0"
langchain = "^0.0.196"
beautifulsoup4 = "^4.12.2"

[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
