[tool.poetry]
name = "aloud"
version = "0.1.0"
description = ""
authors = ["Gilad Barnea <giladbrn@gmail.com>"]
readme = "README.md"



[tool.poetry.dependencies]
python = "^3.11"
langchain = "^0.0.337"
beautifulsoup4 = "^4.12.2"
wikipedia = "^1.4.0"
fake-useragent = "^1.1.3"
unstructured = "^0.7.12"
openai = "^1.3.3"
python-dotenv = "^1.0.0"
html2text = "^2020.1.16"
plum-dispatch = "^2.2.2"
typer = "^0.9.0"

[tool.poetry.group.dev.dependencies]
black = {extras = ["jupyter"], version = "^23.3.0"}
isort = "^5.12.0"
pytest = "^7.4.0"
ipython = "^8.14.0"
jupyter = "^1.0.0"
rich = "^13.4.2"
pdbpp = "^0.10.3"
poethepoet = "^0.24.4"

[tool.poetry.scripts]
aloud = 'aloud.main:main'


[tool.black]
line-length = 120
skip-magic-trailing-comma = true
preview = true

[tool.isort]
profile = "black"

[tool.poe]
envfile = ".env"

[tool.poe.tasks]
test = { cmd = "pytest", env = { COLUMNS = "160" } }
lint = { shell = "black . && isort . " }

[tool.pytest.ini_options]
python_files = ["tests/**/*.py"]
log_format = "[%(levelname)-5s %(asctime)s %(filename)s:%(lineno)d %(funcName)s()] %(message)s"
log_auto_indent = 2
addopts = """
    --color=yes
    --capture=no
    --code-highlight=yes
    --tb=short
    -vv
    --doctest-modules
"""
filterwarnings = ["default:invalid escape sequence:DeprecationWarning"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
