[tool.poetry]
name = "aloud"
version = "0.1.0"
description = ""
authors = ["Gilad Barnea <giladbrn@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
elevenlabs = "^0.2.18"
black = "^23.3.0"
isort = "^5.12.0"
langchain = "^0.0.220"
beautifulsoup4 = "^4.12.2"
wikipedia = "^1.4.0"
fake-useragent = "^1.1.3"
unstructured = "^0.7.12"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"

[tool.black]
line-length = 120
skip-magic-trailing-comma = true
preview = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
