[tool.poetry]
name = "aloud"
version = "0.1.0"
description = ""
authors = ["Gilad Barnea <giladbrn@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
elevenlabs = "^0.2.18"
langchain = "^0.0.226"
beautifulsoup4 = "^4.12.2"
wikipedia = "^1.4.0"
fake-useragent = "^1.1.3"
unstructured = "^0.7.12"
click = "^8.1.4"

[tool.poetry.group.dev.dependencies]
black = {extras = ["jupyter"], version = "^23.3.0"}
isort = "^5.12.0"
pytest = "^7.4.0"
ipython = "^8.14.0"
jupyter = "^1.0.0"
rich = "^13.4.2"

[tool.poetry.scripts]
aloud = 'aloud.main:main'

[tool.black]
line-length = 120
skip-magic-trailing-comma = true
preview = true

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
python_files = ["tests/**/*.py"]
filterwarnings = ["default:invalid escape sequence:DeprecationWarning"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
